require('plugs')
require('settings')
require("tel_find_dirs_config")
require("cheatsheet_config")
require("treesitter_config")
require("telescope_config")
require("which-key_config")
require("projects_config")
require("spectre_config")
require("harpoon_config")
require("lualine_config")
require("pears_config")
require("cmp_config")
require("lsp_config")
require("floaterm_config")
require("remap_template_config")
require("scratchpad_config")

vim.cmd('colorscheme onedark')

nmap("cw", "")
imap("cw", "")
