require("plugs")
require('settings')
require("mr_bowtie.tel_find_dirs")
require("mr_bowtie.cheatsheet")
require("mr_bowtie.treesitter")
require("mr_bowtie.telescope")
require("mr_bowtie.which-key")
require("mr_bowtie.projects")
require("mr_bowtie.spectre")
require("mr_bowtie.harpoon")
require("mr_bowtie.lualine")
require("mr_bowtie.pears")
require("mr_bowtie.cmp")
require("mr_bowtie.lsp")
require("mr_bowtie.floaterm")

vim.cmd("colorscheme onedark")
